"use client";
import { useState, useEffect, useRef, useCallback } from "react";
import { L } from "./i18n";

const TH: Record<string, Record<string, string>> = {
  light: {id:"light",lb:"☀️",bg:"#ffffff",bg2:"#f8fafc",card:"#ffffff",hdr:"rgba(255,255,255,0.92)",input:"#ffffff",muted:"#f1f5f9",brd:"#e2e8f0",brd2:"#f1f5f9",tx:"#0f172a",tx2:"#475569",tx3:"#94a3b8",pri:"#002B7F",priS:"rgba(0,43,127,0.07)",priG:"rgba(0,43,127,0.15)",accG:"rgba(252,209,22,0.2)",grad:"linear-gradient(135deg,#002B7F,#0047d4)",ok:"#059669",okB:"rgba(5,150,105,0.07)",okD:"rgba(5,150,105,0.22)",wn:"#d97706",wnB:"rgba(217,119,6,0.07)",wnD:"rgba(217,119,6,0.22)",er:"#dc2626",erB:"rgba(220,38,38,0.05)",erD:"rgba(220,38,38,0.18)",inf:"#2563eb",infB:"rgba(37,99,235,0.05)",infD:"rgba(37,99,235,0.14)",sh:"0 4px 24px rgba(0,0,0,0.06)",shL:"0 8px 40px rgba(0,0,0,0.08)",dot:"rgba(0,0,0,0.03)",tipBg:"#0f172a",tipTx:"#f1f5f9"},
  dark: {id:"dark",lb:"🌙",bg:"#080c18",bg2:"#0d1224",card:"#111828",hdr:"rgba(8,12,24,0.94)",input:"#111828",muted:"#1a2340",brd:"#1f2b48",brd2:"#162037",tx:"#e8ecf4",tx2:"#8a96b0",tx3:"#4c5b78",pri:"#5b9aff",priS:"rgba(91,154,255,0.1)",priG:"rgba(91,154,255,0.18)",accG:"rgba(252,209,22,0.1)",grad:"linear-gradient(135deg,#2563eb,#5b9aff)",ok:"#3ddba4",okB:"rgba(61,219,164,0.1)",okD:"rgba(61,219,164,0.28)",wn:"#fbbf24",wnB:"rgba(251,191,36,0.1)",wnD:"rgba(251,191,36,0.28)",er:"#ff6b6b",erB:"rgba(255,107,107,0.08)",erD:"rgba(255,107,107,0.22)",inf:"#5b9aff",infB:"rgba(91,154,255,0.08)",infD:"rgba(91,154,255,0.18)",sh:"0 4px 24px rgba(0,0,0,0.3)",shL:"0 8px 40px rgba(0,0,0,0.5)",dot:"rgba(255,255,255,0.02)",tipBg:"#e8ecf4",tipTx:"#0f172a"},
  pink: {id:"pink",lb:"🌸",bg:"#fef1f7",bg2:"#fde4ef",card:"#fff5fa",hdr:"rgba(254,241,247,0.94)",input:"#ffffff",muted:"#fce7f3",brd:"#f5a0cd",brd2:"#f9c6df",tx:"#4a0e2b",tx2:"#8b1a50",tx3:"#c44a83",pri:"#d6246e",priS:"rgba(214,36,110,0.07)",priG:"rgba(214,36,110,0.15)",accG:"rgba(244,114,182,0.2)",grad:"linear-gradient(135deg,#d6246e,#f06daa)",ok:"#059669",okB:"rgba(5,150,105,0.08)",okD:"rgba(5,150,105,0.22)",wn:"#d97706",wnB:"rgba(217,119,6,0.08)",wnD:"rgba(217,119,6,0.22)",er:"#d6246e",erB:"rgba(214,36,110,0.06)",erD:"rgba(214,36,110,0.2)",inf:"#d6246e",infB:"rgba(214,36,110,0.06)",infD:"rgba(214,36,110,0.16)",sh:"0 4px 24px rgba(214,36,110,0.05)",shL:"0 8px 40px rgba(214,36,110,0.1)",dot:"rgba(214,36,110,0.03)",tipBg:"#4a0e2b",tipTx:"#fef1f7"},
};
const TKEYS=["light","dark","pink"];
const LKEYS=["ro","en","fr","de"];

interface Company{cui:string;den:string;reg:string;adr:string;inm:string;tva:boolean;dtva:string|null;drad?:string|null;inact:boolean;dinact?:string|null;efact:boolean;defact:string|null;tvainc:boolean;tvaincP?:string;split:boolean;bpi:boolean;bpiText?:string;risk:number;stare?:string|null;}
type Th=Record<string,string>;
type Lc=Record<string,string>;

const fmtD=(d:string|null|undefined)=>{if(!d||d==="null"||d===" ")return"—";const x=new Date(d);if(isNaN(x.getTime()))return String(d);const m=["ian","feb","mar","apr","mai","iun","iul","aug","sep","oct","nov","dec"];return`${x.getDate()} ${m[x.getMonth()]} ${x.getFullYear()}`};
const rLvl=(s:number)=>s<=30?"ok":s<=60?"wn":"er";
const sC=(k:string,t:Th)=>({ok:{c:t.ok,b:t.okB,d:t.okD},wn:{c:t.wn,b:t.wnB,d:t.wnD},er:{c:t.er,b:t.erB,d:t.erD},inf:{c:t.inf,b:t.infB,d:t.infD}}[k]||{c:t.inf,b:t.infB,d:t.infD});
const nowS=()=>{const n=new Date(),m=["ian","feb","mar","apr","mai","iun","iul","aug","sep","oct","nov","dec"];return`${n.getDate()} ${m[n.getMonth()]} ${n.getFullYear()}, ${String(n.getHours()).padStart(2,"0")}:${String(n.getMinutes()).padStart(2,"0")}`};

const ic=(ch:React.ReactNode,s=20)=>()=><svg width={s} height={s} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">{ch}</svg>;
const I={Search:ic(<><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></>),Shield:ic(<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>),ShieldOk:ic(<><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/></>),ShieldX:ic(<><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m14.5 9.5-5 5"/><path d="m9.5 9.5 5 5"/></>),Building:ic(<><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01M16 6h.01M12 6h.01M12 10h.01M12 14h.01M16 10h.01M16 14h.01M8 10h.01M8 14h.01"/></>),File:ic(<><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/></>),Receipt:ic(<><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 17.5v-11"/></>),Alert:ic(<><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4M12 17h.01"/></>),Card:ic(<><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/></>),Gavel:ic(<><path d="m14 13-7.5 7.5c-.83.83-2.17.83-3 0a2.12 2.12 0 0 1 0-3L11 10"/><path d="m16 16 6-6M8 8l6-6M9 7l8 8M21 11l-8-8"/></>),Gauge:ic(<><path d="m12 14 4-4"/><path d="M3.34 19a10 10 0 1 1 17.32 0"/></>),Down:ic(<><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></>,18),Share:ic(<><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></>,18),Refresh:ic(<><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/></>,16),Back:ic(<><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></>,18),Clock:ic(<><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></>,13),Info:ic(<><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></>,13)};

function ThemeBar({tk,setTk,t}:{tk:string;setTk:(v:string)=>void;t:Th}){return<div style={{display:"flex",gap:3}}>{TKEYS.map(k=><button key={k} onClick={()=>setTk(k)} style={{padding:"5px 10px",borderRadius:7,fontSize:13,fontWeight:700,cursor:"pointer",border:tk===k?`2px solid ${TH[k].pri}`:`1px solid ${t.brd}`,background:tk===k?TH[k].pri:t.muted,color:tk===k?"#fff":t.tx2,fontFamily:"inherit"}}>{TH[k].lb}</button>)}</div>}

function LangBar({lk,setLk,t}:{lk:string;setLk:(v:string)=>void;t:Th}){return<div style={{display:"flex",gap:2}}>{LKEYS.map(k=><button key={k} onClick={()=>setLk(k)} style={{padding:"4px 8px",borderRadius:6,fontSize:11,fontWeight:800,cursor:"pointer",border:lk===k?`2px solid ${t.pri}`:`1px solid ${t.brd}`,background:lk===k?t.priS:"transparent",color:lk===k?t.pri:t.tx3,fontFamily:"inherit"}}>{L[k].flag} {L[k].lb}</button>)}</div>}

function Badge({status,t,l,size="md"}:{status:string;t:Th;l:Lc;size?:string}){const lb:Record<string,string>={ok:l.badgeOk,wn:l.badgeWarn,er:l.badgeRisk,inf:l.badgeInfo};const sc=sC(status,t);const sz=size==="lg"?{px:16,py:8,fs:13}:size==="sm"?{px:8,py:3,fs:10}:{px:12,py:5,fs:11};return<span style={{display:"inline-flex",alignItems:"center",gap:5,borderRadius:99,fontWeight:800,textTransform:"uppercase",letterSpacing:".05em",padding:`${sz.py}px ${sz.px}px`,fontSize:sz.fs,color:sc.c,background:sc.b,border:`1px solid ${sc.d}`}}><span style={{width:6,height:6,borderRadius:99,background:sc.c,animation:status==="er"?"pulse 2s infinite":"none"}}/>{lb[status]||"Info"}</span>}

function Tip({text,children,t}:{text:string;children:React.ReactNode;t:Th}){const[s,setS]=useState(false);return<span style={{position:"relative",display:"inline-flex"}} onMouseEnter={()=>setS(true)} onMouseLeave={()=>setS(false)}>{children}{s&&<span style={{position:"absolute",bottom:"calc(100% + 8px)",left:"50%",transform:"translateX(-50%)",padding:"10px 14px",fontSize:11,borderRadius:10,lineHeight:1.5,background:t.tipBg,color:t.tipTx,boxShadow:"0 8px 30px rgba(0,0,0,.25)",zIndex:50,width:240,textAlign:"center",pointerEvents:"none",fontWeight:500}}>{text}</span>}</span>}

function RGauge({score,t}:{score:number;t:Th}){const rk=rLvl(score);const c=sC(rk,t).c;const a=-90+(score/100)*180;return<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><div style={{width:115,height:58,overflow:"hidden"}}><svg viewBox="0 0 120 62" style={{width:"100%",height:"100%"}}><path d="M 10 57 A 50 50 0 0 1 110 57" fill="none" stroke={t.brd} strokeWidth="8" strokeLinecap="round"/><path d="M 10 57 A 50 50 0 0 1 110 57" fill="none" stroke={c} strokeWidth="8" strokeLinecap="round" strokeDasharray={`${(score/100)*157} 157`} style={{transition:"stroke-dasharray 1s ease"}}/><line x1="60" y1="57" x2="60" y2="18" stroke={c} strokeWidth="2.5" strokeLinecap="round" style={{transformOrigin:"60px 57px",transform:`rotate(${a}deg)`,transition:"transform 1s ease"}}/><circle cx="60" cy="57" r="4" fill={c}/></svg></div><div><span style={{fontSize:24,fontWeight:900,color:c}}>{score}</span><span style={{fontSize:11,color:t.tx3}}>/100</span></div></div>}

function CCard({icon:Icon,title,status,main,sub,tip,delay=0,t,l}:{icon:React.ComponentType;title:string;status:string;main:string;sub?:string;tip?:string;delay?:number;t:Th;l:Lc}){const[vis,setVis]=useState(false);useEffect(()=>{const x=setTimeout(()=>setVis(true),delay);return()=>clearTimeout(x)},[delay]);const sc=sC(status,t);return<div style={{borderRadius:16,border:`1px solid ${sc.d}`,padding:20,background:t.card,opacity:vis?1:0,transform:vis?"translateY(0)":"translateY(14px)",transition:"all .35s ease"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div style={{padding:8,borderRadius:12,background:sc.b,color:sc.c}}><Icon/></div><Badge status={status} t={t} l={l}/></div><h3 style={{fontWeight:800,color:t.tx,marginBottom:4,fontSize:13}}>{title}</h3><p style={{fontSize:13,color:t.tx2,marginBottom:3,fontWeight:600,lineHeight:1.4}}>{main}</p>{sub&&<p style={{fontSize:12,color:t.tx3,lineHeight:1.4}}>{sub}</p>}{tip&&<div style={{marginTop:12,paddingTop:12,borderTop:`1px solid ${t.brd2}`}}><Tip text={tip} t={t}><button style={{display:"flex",alignItems:"center",gap:4,fontSize:12,color:t.pri,fontWeight:600,background:"none",border:"none",cursor:"pointer",padding:0,fontFamily:"inherit"}}><I.Info/> {l.whyMatters}</button></Tip></div>}</div>}

function Loading({t,l}:{t:Th;l:Lc}){return<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"80px 20px",gap:22,minHeight:"80vh"}}><div style={{width:68,height:68,borderRadius:18,background:t.grad,display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",boxShadow:`0 8px 36px ${t.priG}`,animation:"pulse 1.5s infinite"}}><I.Shield/></div><div style={{textAlign:"center"}}><p style={{fontSize:17,fontWeight:800,color:t.tx,marginBottom:4}}>{l.loadingTitle}</p><p style={{fontSize:13,color:t.tx3}}>{l.loadingSub}</p></div><div style={{display:"flex",gap:4}}>{[0,1,2,3,4].map(i=><div key={i} style={{width:7,height:7,borderRadius:99,background:t.pri,animation:`bounce 1s infinite ${i*.15}s`}}/>)}</div></div>}

function ErrorMsg({msg,onBack,t,l}:{msg:string;onBack:()=>void;t:Th;l:Lc}){return<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"80px 20px",gap:16,minHeight:"60vh"}}><div style={{width:56,height:56,borderRadius:14,background:t.erB,display:"flex",alignItems:"center",justifyContent:"center",color:t.er}}><I.Alert/></div><p style={{fontSize:16,fontWeight:700,color:t.tx,textAlign:"center",maxWidth:400}}>{msg}</p><button onClick={onBack} style={{padding:"10px 24px",borderRadius:12,fontWeight:700,fontSize:14,border:"none",cursor:"pointer",background:t.grad,color:"#fff",fontFamily:"inherit"}}>{l.btnTryAgain}</button></div>}

function Home({onCheck,tk,setTk,lk,setLk,t,l}:{onCheck:(c:string)=>void;tk:string;setTk:(v:string)=>void;lk:string;setLk:(v:string)=>void;t:Th;l:Lc}){const[cui,setCui]=useState("");const[err,setErr]=useState("");const ref=useRef<HTMLInputElement>(null);useEffect(()=>{ref.current?.focus()},[]);const go=()=>{const c=cui.replace(/\s|RO/gi,"");if(!c||!/^\d{1,10}$/.test(c)){setErr(l.errInvalid);return;}setErr("");onCheck(c)};
return<><header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 20px",borderBottom:`1px solid ${t.brd2}`,background:t.hdr,backdropFilter:"blur(16px)"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:32,height:32,borderRadius:9,background:t.grad,display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",boxShadow:`0 4px 14px ${t.priG}`}}><I.ShieldOk/></div><div><div style={{fontWeight:900,color:t.tx,fontSize:15}}>{l.title}</div><div style={{fontSize:9,color:t.tx3,textTransform:"uppercase",letterSpacing:".1em",fontWeight:600}}>{l.subtitle}</div></div></div><div style={{display:"flex",alignItems:"center",gap:6}}><LangBar lk={lk} setLk={setLk} t={t}/><ThemeBar tk={tk} setTk={setTk} t={t}/></div></header>
<main style={{display:"flex",flexDirection:"column",alignItems:"center",padding:"64px 20px 40px",position:"relative"}}><div style={{position:"absolute",top:-200,right:-200,width:480,height:480,borderRadius:"50%",background:t.priG,filter:"blur(120px)",pointerEvents:"none"}}/><div style={{position:"absolute",bottom:-150,left:-150,width:380,height:380,borderRadius:"50%",background:t.accG,filter:"blur(100px)",pointerEvents:"none"}}/>
<div style={{textAlign:"center",marginBottom:36,maxWidth:580,position:"relative",zIndex:1,animation:"slideUp .6s ease"}}><div style={{display:"inline-flex",alignItems:"center",gap:7,padding:"5px 13px",borderRadius:99,background:t.priS,color:t.pri,fontSize:11,fontWeight:800,marginBottom:22,border:`1px solid ${t.infD}`}}><span style={{width:5,height:5,borderRadius:99,background:t.pri,animation:"pulse 2s infinite"}}/> {l.liveBadge}</div><h2 style={{fontSize:42,fontWeight:900,color:t.tx,marginBottom:14,lineHeight:1.08,letterSpacing:"-.03em"}}>{l.heroTitle1}<span style={{display:"block",background:t.grad,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",backgroundClip:"text"}}>{l.heroTitle2}</span></h2><p style={{fontSize:16,color:t.tx2,maxWidth:460,margin:"0 auto",lineHeight:1.6}}>{l.heroDesc}</p></div>
<div style={{width:"100%",maxWidth:520,position:"relative",zIndex:1,animation:"slideUp .6s ease .15s both"}}><div style={{display:"flex",alignItems:"center",background:t.input,borderRadius:16,boxShadow:t.shL,border:`2px solid ${t.brd}`,overflow:"hidden"}}><div style={{paddingLeft:18,color:t.tx3}}><I.Search/></div><input ref={ref} value={cui} onChange={e=>{setCui(e.target.value);setErr("")}} onKeyDown={e=>e.key==="Enter"&&go()} placeholder={l.placeholder} style={{flex:1,padding:"16px 14px",background:"transparent",border:"none",outline:"none",color:t.tx,fontSize:15,fontWeight:500,fontFamily:"inherit"}}/><button onClick={go} style={{margin:5,padding:"13px 24px",borderRadius:13,fontWeight:800,color:"#fff",fontSize:14,border:"none",cursor:"pointer",background:t.grad,boxShadow:`0 4px 14px ${t.priG}`,fontFamily:"inherit"}}>{l.btnCheck}</button></div>{err&&<p style={{marginTop:10,fontSize:13,color:t.er,fontWeight:600,textAlign:"center",display:"flex",alignItems:"center",justifyContent:"center",gap:5,animation:"shake .4s ease"}}><I.Alert/> {err}</p>}</div>
<div style={{marginTop:50,display:"flex",gap:28,color:t.tx3,position:"relative",zIndex:1,animation:"slideUp .6s ease .45s both",flexWrap:"wrap",justifyContent:"center"}}>{["ANAF","ONRC","BPI","RO e-Factura"].map(s=><div key={s} style={{display:"flex",alignItems:"center",gap:5,fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:".06em"}}><I.ShieldOk/> {s}</div>)}</div></main>
<div style={{textAlign:"center",padding:"10px 20px",fontSize:11,color:t.tx3,borderTop:`1px solid ${t.brd2}`}}>{l.disclaimer}</div>
<footer style={{textAlign:"center",padding:"16px 20px",borderTop:`1px solid ${t.brd2}`,fontSize:12,color:t.tx3}}><span style={{fontWeight:700}}>CUI Check © 2026</span>{" • "}Calculator Salarial{" • "}Clasificare COR{" • "}{l.footer}</footer></>}

function Dash({co,onBack,tk,setTk,lk,setLk,t,l}:{co:Company;onBack:()=>void;tk:string;setTk:(v:string)=>void;lk:string;setLk:(v:string)=>void;t:Th;l:Lc}){const[copied,setCopied]=useState(false);const rk=rLvl(co.risk);const rc=sC(rk,t);const ts=nowS();const copy=()=>{setCopied(true);setTimeout(()=>setCopied(false),2000)};
const riskLabel=rk==="ok"?l.riskLow:rk==="wn"?l.riskMed:l.riskHigh;
const cards=[
{icon:I.Building,title:l.cardIdent,status:"inf",main:co.den,sub:`${co.reg} • ${co.adr}${co.stare?` • ${co.stare}`:""}`,delay:100},
{icon:I.Receipt,title:l.cardTVA,status:co.tva?"ok":"er",main:co.tva?`${l.tvaYes}${co.dtva&&co.dtva!==" "?` ${l.tvaFrom} ${fmtD(co.dtva)}`:""}`:`${l.tvaNo}${co.drad&&co.drad!==" "?` — ${l.tvaRevoked} ${fmtD(co.drad)}`:""}`,sub:co.tva?l.tvaSub:l.tvaSubNo,tip:l.tvaTip,delay:200},
{icon:co.inact?I.ShieldX:I.ShieldOk,title:l.cardInact,status:co.inact?"er":"ok",main:co.inact?`${l.inactYes}${co.dinact&&co.dinact!==" "?` ${l.tvaFrom} ${fmtD(co.dinact)}`:""}`:`${l.inactNo}`,sub:co.inact?l.inactSub:l.inactSubNo,tip:l.inactTip,delay:300},
{icon:I.File,title:l.cardEfact,status:co.efact?"ok":"er",main:co.efact?`${l.efactYes}${co.defact&&co.defact!==" "?` ${l.tvaFrom} ${fmtD(co.defact)}`:""}`:`${l.efactNo}`,sub:co.efact?l.efactSub:l.efactSubNo,tip:l.efactTip,delay:400},
{icon:I.Card,title:l.cardTvaInc,status:co.tvainc?"wn":"ok",main:co.tvainc?`${l.tvaIncYes}${co.tvaincP?` (${co.tvaincP})`:""}`:`${l.tvaIncNo}`,sub:co.tvainc?l.tvaIncSub:l.tvaIncSubNo,tip:l.tvaIncTip,delay:500},
{icon:I.Receipt,title:l.cardSplit,status:co.split?"wn":"ok",main:co.split?l.splitYes:l.splitNo,sub:co.split?l.splitSub:l.splitSubNo,tip:l.splitTip,delay:600},
{icon:I.Gavel,title:l.cardBPI,status:co.bpi?"er":"ok",main:co.bpi?l.bpiYes:l.bpiNo,sub:co.bpi?co.bpiText:l.bpiSub,tip:l.bpiTip,delay:700},
];
return<><header style={{position:"sticky",top:0,zIndex:20,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 20px",borderBottom:`1px solid ${t.brd2}`,backdropFilter:"blur(16px)",background:t.hdr}}><div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={onBack} style={{padding:7,borderRadius:9,border:"none",background:"transparent",color:t.tx3,cursor:"pointer",display:"flex"}}><I.Back/></button><div style={{width:28,height:28,borderRadius:7,background:t.grad,display:"flex",alignItems:"center",justifyContent:"center",color:"#fff"}}><I.ShieldOk/></div><span style={{fontWeight:900,color:t.tx,fontSize:13}}>{l.title}</span></div><div style={{display:"flex",alignItems:"center",gap:5}}><button onClick={()=>window.open("/api/report?cui="+co.cui+"&lang="+lk,"_blank")} style={{display:"inline-flex",alignItems:"center",gap:7,padding:"8px 15px",borderRadius:11,fontWeight:700,fontSize:12,cursor:"pointer",border:"none",background:t.grad,color:"#fff",boxShadow:`0 4px 14px ${t.priG}`,fontFamily:"inherit"}}><I.Down/> {l.btnReport}</button><button onClick={copy} style={{display:"inline-flex",alignItems:"center",gap:7,padding:"8px 15px",borderRadius:11,fontWeight:700,fontSize:12,cursor:"pointer",border:`1px solid ${t.brd}`,background:"transparent",color:t.tx2,fontFamily:"inherit"}}>{copied?`✓ ${l.btnCopied}`:<><I.Share/> {l.btnShare}</>}</button><LangBar lk={lk} setLk={setLk} t={t}/><ThemeBar tk={tk} setTk={setTk} t={t}/></div></header>
<main style={{maxWidth:1080,margin:"0 auto",padding:"28px 20px"}}><div style={{marginBottom:24,animation:"slideUp .5s ease"}}><h1 style={{fontSize:26,fontWeight:900,color:t.tx,letterSpacing:"-.02em",marginBottom:6}}>{co.den}</h1><div style={{display:"flex",flexWrap:"wrap",alignItems:"center",gap:8}}><span style={{padding:"4px 11px",borderRadius:9,background:t.priS,color:t.pri,fontSize:13,fontWeight:700,fontFamily:"monospace",border:`1px solid ${t.infD}`}}>CUI {co.cui}</span><span style={{fontSize:13,color:t.tx3}}>{co.reg} • {co.adr}</span></div></div>
<div style={{marginBottom:24,borderRadius:16,border:`1px solid ${rc.d}`,padding:22,background:rc.b,animation:"slideUp .5s ease .1s both"}}><div style={{display:"flex",flexWrap:"wrap",alignItems:"center",justifyContent:"space-between",gap:20}}><div style={{display:"flex",alignItems:"center",gap:20}}><RGauge score={co.risk} t={t}/><div><h2 style={{fontSize:19,fontWeight:900,color:t.tx,marginBottom:3}}>{rk==="ok"?l.summaryOk:rk==="wn"?l.summaryWarn:l.summaryBad}</h2><p style={{fontSize:13,color:t.tx2}}>{l.riskAgg}</p><span style={{fontSize:10,fontWeight:800,textTransform:"uppercase",letterSpacing:".06em",color:rc.c}}>{riskLabel}</span></div></div><div style={{textAlign:"right",fontSize:12,color:t.tx3}}><div style={{display:"flex",alignItems:"center",gap:4,justifyContent:"flex-end"}}><I.Clock/> {ts}</div></div></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:14,marginBottom:24}}>{cards.map((c,i)=><CCard key={i}{...c} t={t} l={l}/>)}<div style={{borderRadius:16,border:`1px solid ${rc.d}`,padding:22,background:rc.b,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8,animation:"slideUp .5s ease .8s both"}}><div style={{color:rc.c}}><I.Gauge/></div><h3 style={{fontWeight:800,color:t.tx,fontSize:14}}>{l.cardGeneral}</h3><Badge status={rk} t={t} l={l} size="lg"/><p style={{fontSize:12,color:t.tx3,textAlign:"center"}}>{rk==="ok"?l.allOk:rk==="wn"?l.needsAtt:l.multiProb}</p></div></div>
<div style={{textAlign:"center",fontSize:11,color:t.tx3,padding:"20px 0",marginTop:16,borderTop:`1px solid ${t.brd2}`}}>{l.liveAnaf} {ts}</div></main></>}

export default function Page(){const[page,setPage]=useState("home");const[tk,setTk]=useState("light");const[lk,setLk]=useState("ro");const[co,setCo]=useState<Company|null>(null);const[error,setError]=useState("");const t=TH[tk];const l=L[lk];
const check=useCallback(async(cui:string)=>{setPage("loading");setError("");try{const res=await fetch(`/api/check-cui?cui=${cui}`);const data=await res.json();if(!res.ok){setError(data.error||l.errUnknown);setPage("error");return;}setCo(data as Company);setPage("dash")}catch{setError(l.errNetwork);setPage("error")}},[l]);
return(<div style={{background:t.bg,color:t.tx,minHeight:"100vh",fontFamily:"system-ui,-apple-system,sans-serif",transition:"background .3s,color .3s"}}><style>{`@keyframes slideUp{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}@keyframes shake{0%,100%{transform:translateX(0)}25%{transform:translateX(-4px)}75%{transform:translateX(4px)}}@keyframes bounce{0%,80%,100%{transform:translateY(0)}40%{transform:translateY(-5px)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}`}</style>
{page==="home"&&<Home onCheck={check} tk={tk} setTk={setTk} lk={lk} setLk={setLk} t={t} l={l}/>}
{page==="loading"&&<Loading t={t} l={l}/>}
{page==="error"&&<ErrorMsg msg={error} onBack={()=>setPage("home")} t={t} l={l}/>}
{page==="dash"&&co&&<Dash co={co} onBack={()=>setPage("home")} tk={tk} setTk={setTk} lk={lk} setLk={setLk} t={t} l={l}/>}
</div>)}
